### ISSUE TITLE
Typo for command to push modified image to define.

### ISSUE THREAD

**Issue by shina-m** [jdkruzr/BooxPalma2RootGuide#1]
Hello @jdkruzr. Thank you so much for putting this guide together. I noticed a typo for the command to push the magisk-boot images to the device.

The it should be `/pboot_X` instead of `/pbootX` where X is either `a` or `b`.
 i.e. `.\edl /u /w /pboot_a magisk-boota.img` instead of  `.\edl /u /w /pboota magisk-boota.img` and likewise for boot b.

Other than this everything else worked perfectly.

**Comment by jdkruzr** [comment]
you're right, thank you!
